---
name: Notify twitter

on:
  # Run on Pull requests:
  pull_request:
    branches: [ main ]

  # Run when manually triggered
  workflow_dispatch:

env:
  THIS_REPO: ${{ github.repository }}
  THIS_SERVER: $${{ github.server }}

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "ðŸŽ‰ New Pull Request in ${{ env.THIS_REPO }}! You can check it out here: ${{ env.THIS_SERVER }}/${{ env.THIS_REPO }}" 
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
